<a href="https://colab.research.google.com/github/PolinaLukyanova/pythonGB/blob/main/Homework_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Задача 44: 
- В ячейке ниже представлен код генерирующий DataFrame, которая состоит всего
из 1 столбца. Ваша задача перевести его в one hot вид. Сможете ли вы это сделать без
get_dummies?

In [53]:
import pandas as pd
import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data.head(20)

   whoAmI
0   human
1   robot
2   human
3   human
4   human
5   robot
6   human
7   robot
8   robot
9   robot
10  robot
11  robot
12  robot
13  robot
14  human
15  human
16  robot
17  human
18  human
19  human

In [54]:
data.loc[data['whoAmI'] == 'human', 'human'] = True
data.loc[data['whoAmI'] == 'robot', 'robot'] = True
data[['human', 'robot']].notnull()

    human  robot
0    True  False
1   False   True
2    True  False
3    True  False
4    True  False
5   False   True
6    True  False
7   False   True
8   False   True
9   False   True
10  False   True
11  False   True
12  False   True
13  False   True
14   True  False
15   True  False
16  False   True
17   True  False
18   True  False
19   True  False